package com.test.thecocktaildb.presentationNew.model

@Suppress("unused")
enum class CocktailIngredient(val key: String) {
    LIGHT_RUM("Light rum"),
    APPLEJACK("Applejack"),
    GIN("Gin"),
    DARK_RUM("Dark rum"),
    SWEET_VERMOUTH("Sweet Vermouth"),
    STRAWBERRY_SCHNAPPS("Strawberry schnapps"),
    SCOTCH("Scotch"),
    APRICOT_BRANDY("Apricot brandy"),
    TRIPLE_SEC("Triple sec"),
    SOUTHERN_COMFORT("Southern Comfort"),
    ORANGE_BITTERS("Orange bitters"),
    BRANDY("Brandy"),
    LEMON_VODKA("Lemon vodka"),
    BLENDED_WHISKEY("Blended whiskey"),
    DRY_VERMOUTH("Dry Vermouth"),
    AMARETTO("Amaretto"),
    TEA("Tea"),
    CHAMPAGNE("Champagne"),
    COFFEE_LIQUEUR("Coffee liqueur"),
    BOURBON("Bourbon"),
    TEQUILA("Tequila"),
    VODKA("Vodka"),
    ANEJO_RUM("Añejo rum"),
    BITTERS("Bitters"),
    SUGAR("Sugar"),
    KAHLUA("Kahlua"),
    DEMERARA_SUGAR("demerara Sugar"),
    DUBONNET_ROUGE("Dubonnet Rouge"),
    LIME_JUICE("Lime juice"),
    IRISH_WHISKEY("Irish whiskey"),
    APPLE_BRANDY("Apple brandy"),
    CARBONATED_WATER("Carbonated water"),
    CHERRY_BRANDY("Cherry brandy"),
    CREME_DE_CACAO("Creme de Cacao"),
    GRENADINE("Grenadine"),
    PORT("Port"),
    COFFEE_BRANDY("Coffee brandy"),
    RED_WINE("Red wine"),
    RUM("Rum"),
    GRAPEFRUIT_JUICE("Grapefruit juice"),
    RICARD("Ricard"),
    SHERRY("Sherry"),
    COGNAC("Cognac"),
    SLOE_GIN("Sloe gin"),
    APPLE_JUICE("Apple juice"),
    PINEAPPLE_JUICE("Pineapple juice"),
    LEMON_JUICE("Lemon juice"),
    SUGAR_SYRUP("Sugar syrup"),
    MILK("Milk"),
    STRAWBERRIES("Strawberries"),
    CHOCOLATE_SYRUP("Chocolate syrup"),
    YOGHURT("Yoghurt"),
    MANGO("Mango"),
    GINGER("Ginger"),
    LIME("Lime"),
    CANTALOUPE("Cantaloupe"),
    BERRIES("Berries"),
    GRAPES("Grapes"),
    KIWI("Kiwi"),
    TOMATO_JUICE("Tomato juice"),
    COCOA_POWDER("Cocoa powder"),
    CHOCOLATE("Chocolate"),
    HEAVY_CREAM("Heavy cream"),
    GALLIANO("Galliano"),
    PEACH_VODKA("Peach Vodka"),
    OUZO("Ouzo"),
    COFFEE("Coffee"),
    SPICED_RUM("Spiced rum"),
    WATER("Water"),
    ESPRESSO("Espresso"),
    ANGELICA_ROOT("Angelica root"),
    ORANGE("Orange"),
    CRANBERRIES("Cranberries"),
    JOHNNIE_WALKER("Johnnie Walker"),
    APPLE_CIDER("Apple cider"),
    EVERCLEAR("Everclear"),
    CRANBERRY_JUICE("Cranberry juice"),
    EGG_YOLK("Egg yolk"),
    EGG("Egg"),
    GRAPE_JUICE("Grape juice"),
    PEACH_NECTAR("Peach nectar"),
    LEMON("Lemon"),
    FIREWATER("Firewater"),
    LEMONADE("Lemonade"),
    LAGER("Lager"),
    WHISKEY("Whiskey"),
    ABSOLUT_CITRON("Absolut Citron"),
    PISCO("Pisco"),
    IRISH_CREAM("Irish cream"),
    ALE("Ale"),
    CHOCOLATE_LIQUEUR("Chocolate liqueur"),
    MIDORI_MELON_LIQUEUR("Midori melon liqueur"),
    SAMBUCA("Sambuca"),
    CIDER("Cider"),
    SPRITE("Sprite"),
    SEVEN_UP("7-Up"),
    BLACKBERRY_BRANDY("Blackberry brandy"),
    PEPPERMINT_SCHNAPPS("Peppermint schnapps"),
    CREME_DE_CASSIS("Creme de Cassis"),
    JACK_DANIELS("Jack Daniels"),
    UNDEFINED("")
}